server:
  port: 8082
spring:
  application:
    name: Discount
  datasource:
    url: jdbc:mysql://localhost:3306/discount
    username: Sina
    password: S1p3zz@198486#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20